import albumDesignImage from "../assets/images/gallery/album-design.webp";
import digitalEditingImage from "../assets/images/gallery/digital-editing.webp";
import passportPhotosImage from "../assets/images/gallery/passport-photos.webp";
import premiumFrameImage from "../assets/images/gallery/premium-frame.webp";
import printSupportImage from "../assets/images/gallery/print-lamination-support.webp";
import restorationImage from "../assets/images/gallery/restoration-before-after.webp";
import studioPortraitImage from "../assets/images/gallery/studio-portrait.webp";

export const STUDIO_CATEGORIES = [
  "All",
  "Photo Enhancement",
  "Digital Paintings",
  "Wedding Banners",
  "Double Exposure",
  "Wedding Designs",
  "Wedding Card Design",
  "Chibi Style",
  "Studio Design",
];

export const STUDIO_CREDIT_INR = 13;

export const OUTPUT_RATIOS = {
  "2:3": {
    id: "2:3",
    label: "Portrait",
    dimensions: "2:3",
    orientation: "portrait",
  },
  "3:2": {
    id: "3:2",
    label: "Landscape",
    dimensions: "3:2",
    orientation: "landscape",
  },
  "1:1": {
    id: "1:1",
    label: "Square",
    dimensions: "1:1",
    orientation: "square",
  },
  "4:5": {
    id: "4:5",
    label: "Portrait",
    dimensions: "4:5",
    orientation: "portrait-soft",
  },
  "9:16": {
    id: "9:16",
    label: "Story",
    dimensions: "9:16",
    orientation: "story",
  },
  "16:9": {
    id: "16:9",
    label: "Widescreen",
    dimensions: "16:9",
    orientation: "widescreen",
  },
};

export const studioStyles = [
  {
    id: "classic-painting",
    generationPreset: "classic-painting",
    generationMode: "single_portrait_style",
    name: "Quality Photo Enhance",
    category: "Photo Enhancement",
    thumbnail: restorationImage,
    thumbnailPosition: "center",
    accent: "violet",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Restore blur, recover natural detail, and enhance your photo with a crisp professional DSLR-quality finish.",
    tags: ["photo enhancement", "restoration", "dslr", "sharpness"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-red-petal",
    generationPreset: "digital-painting-red-petal",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Red Petal",
    category: "Digital Paintings",
    thumbnail: studioPortraitImage,
    thumbnailPosition: "50% 28%",
    accent: "rose",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Rich crimson accents and delicate petal-inspired detail.",
    tags: ["red", "petals", "romantic", "portrait"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-tropical",
    generationPreset: "digital-painting-tropical",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Tropical",
    category: "Digital Paintings",
    thumbnail: printSupportImage,
    thumbnailPosition: "center",
    accent: "cyan",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Lush color, warm light and contemporary botanical styling.",
    tags: ["tropical", "green", "bright", "nature"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-royal-pink",
    generationPreset: "digital-painting-royal-pink",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Royal Pink",
    category: "Digital Paintings",
    thumbnail: premiumFrameImage,
    thumbnailPosition: "center",
    accent: "pink",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3"],
    description: "A polished royal portrait treatment with luminous pink tones.",
    tags: ["royal", "pink", "elegant", "luxury"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-forest-green",
    generationPreset: "digital-painting-forest-green",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Forest Green",
    category: "Digital Paintings",
    thumbnail: passportPhotosImage,
    thumbnailPosition: "center",
    accent: "emerald",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Deep forest color grading with a refined editorial finish.",
    tags: ["forest", "green", "editorial", "premium"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-pastel-cloud",
    generationPreset: "digital-painting-pastel-cloud",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Pastel Cloud",
    category: "Digital Paintings",
    thumbnail: digitalEditingImage,
    thumbnailPosition: "center",
    accent: "sky",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Airy pastel color with soft cloud-like texture and light.",
    tags: ["pastel", "cloud", "soft", "dreamy"],
    isActive: true,
    isFree: false,
  },
  {
    id: "digital-painting-aurora",
    generationPreset: "digital-painting-aurora",
    generationMode: "single_portrait_style",
    name: "Digital Painting - Aurora",
    category: "Digital Paintings",
    thumbnail: albumDesignImage,
    thumbnailPosition: "center",
    accent: "aurora",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "Vivid cyan and violet light inspired by the northern sky.",
    tags: ["aurora", "neon", "colorful", "cinematic"],
    isActive: true,
    isFree: false,
  },
  {
    id: "wedding-banner-elegance",
    generationPreset: "wedding-banner-elegance",
    generationMode: "banner_or_template_style",
    name: "Wedding Banner - Elegance",
    category: "Wedding Banners",
    thumbnail: premiumFrameImage,
    thumbnailPosition: "center",
    accent: "gold",
    credits: 4,
    photosRequired: 2,
    supportedRatios: ["3:2"],
    description: "A spacious celebration banner composed for two portraits.",
    tags: ["wedding", "banner", "couple", "landscape"],
    isActive: true,
    isFree: false,
  },
  {
    id: "double-exposure-dreamscape",
    generationPreset: "double-exposure-dreamscape",
    generationMode: "double_image_composition",
    name: "Double Exposure - Dreamscape",
    category: "Double Exposure",
    thumbnail: restorationImage,
    thumbnailPosition: "center",
    accent: "indigo",
    credits: 4,
    photosRequired: 2,
    supportedRatios: ["2:3", "3:2"],
    description: "Layered silhouette styling with atmospheric scenic depth.",
    tags: ["double exposure", "dreamscape", "silhouette", "art"],
    isActive: true,
    isFree: false,
  },
  {
    id: "wedding-design-celebration",
    generationPreset: "wedding-design-celebration",
    generationMode: "banner_or_template_style",
    name: "Wedding Design - Celebration",
    category: "Wedding Designs",
    thumbnail: studioPortraitImage,
    thumbnailPosition: "50% 25%",
    accent: "rose",
    credits: 4,
    photosRequired: 2,
    supportedRatios: ["2:3", "3:2"],
    description: "A premium couple composition with festive framing and light.",
    tags: ["wedding", "celebration", "couple", "festive"],
    isActive: true,
    isFree: false,
  },
  {
    id: "wedding-card-minimal-bloom",
    generationPreset: "wedding-card-minimal-bloom",
    generationMode: "banner_or_template_style",
    name: "Wedding Card - Minimal Bloom",
    category: "Wedding Card Design",
    thumbnail: albumDesignImage,
    thumbnailPosition: "center",
    accent: "lilac",
    credits: 4,
    photosRequired: 2,
    supportedRatios: ["2:3"],
    description: "Elegant invitation-inspired composition with subtle florals.",
    tags: ["wedding card", "invitation", "floral", "minimal"],
    isActive: true,
    isFree: false,
  },
  {
    id: "chibi-happy-day",
    generationPreset: "chibi-happy-day",
    generationMode: "single_portrait_style",
    name: "Chibi Style - Happy Day",
    category: "Chibi Style",
    thumbnail: digitalEditingImage,
    thumbnailPosition: "center",
    accent: "amber",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "A cheerful, playful character look with bright color energy.",
    tags: ["chibi", "cute", "character", "playful"],
    isActive: true,
    isFree: false,
  },
  {
    id: "studio-design-clean-light",
    generationPreset: "studio-design-clean-light",
    generationMode: "single_portrait_style",
    name: "Studio Design - Clean Light",
    category: "Studio Design",
    thumbnail: passportPhotosImage,
    thumbnailPosition: "center",
    accent: "cyan",
    credits: 3,
    photosRequired: 1,
    supportedRatios: ["2:3", "3:2"],
    description: "A clean studio treatment for testing the complete design flow.",
    tags: ["studio", "clean", "portrait", "professional"],
    isActive: true,
    isFree: false,
  },
];

export const getStudioStyleById = (styleId) =>
  studioStyles.find((style) => style.id === styleId) || null;

export const formatStudioPrice = (style) => {
  if (!style) {
    return "";
  }

  const creditLabel = style.credits === 1 ? "Credit" : "Credits";
  return `${style.credits} ${creditLabel} · ₹${style.credits * STUDIO_CREDIT_INR}`;
};
